package exercicio2;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Poupex extends javax.swing.JFrame {
    /**     * Creates new form Poupex
     */
    public Poupex() {
        initComponents();
        getContentPane().setBackground(Color.BLACK); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        textoJurosMes = new javax.swing.JLabel();
        textoNumAnos = new javax.swing.JLabel();
        textoDeposito = new javax.swing.JLabel();
        cxJurosMes = new javax.swing.JTextField();
        cxNumAnos = new javax.swing.JTextField();
        cxDepMensal = new javax.swing.JTextField();
        botaoResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setName(""); // NOI18N

        textoJurosMes.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        textoJurosMes.setForeground(new java.awt.Color(255, 255, 255));
        textoJurosMes.setText("Juros ao mês %:  ");

        textoNumAnos.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        textoNumAnos.setForeground(new java.awt.Color(255, 255, 255));
        textoNumAnos.setText("Num. de anos: ");

        textoDeposito.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        textoDeposito.setForeground(new java.awt.Color(255, 255, 255));
        textoDeposito.setText("Depósito Mensal R$: ");

        cxJurosMes.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        cxJurosMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxJurosMesActionPerformed(evt);
            }
        });

        cxNumAnos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        cxNumAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumAnosActionPerformed(evt);
            }
        });

        cxDepMensal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        cxDepMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDepMensalActionPerformed(evt);
            }
        });

        botaoResultado.setBackground(new java.awt.Color(255, 0, 0));
        botaoResultado.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        botaoResultado.setForeground(new java.awt.Color(255, 255, 255));
        botaoResultado.setText("OK");
        botaoResultado.setToolTipText("");
        botaoResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoResultado.setContentAreaFilled(false);
        botaoResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoResultado.setOpaque(true);
        botaoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxDepMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botaoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoNumAnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoJurosMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxJurosMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxNumAnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoJurosMes)
                    .addComponent(cxJurosMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNumAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxNumAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDeposito)
                    .addComponent(cxDepMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxDepMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDepMensalActionPerformed
         
    }//GEN-LAST:event_cxDepMensalActionPerformed

    private void cxNumAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumAnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumAnosActionPerformed

    private void cxJurosMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxJurosMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxJurosMesActionPerformed

    private void botaoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResultadoActionPerformed
        double deposito1 = 0, numAnos = 0, jurosMes = 0;
        boolean flag = true;
        while (flag){
            String deposito = cxDepMensal.getText().replace(',', '.');
            if (!deposito.isEmpty()){
                try{
                    deposito1 = Double.parseDouble(deposito);
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "O valor é invalido, digite apenas números.", "Depósito", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "O valor não pode ser vazio.", "Depósito", JOptionPane.ERROR_MESSAGE);
                break;
            }
            String num = cxNumAnos.getText().replace(',', '.');
            if (!num.isEmpty() && num.chars().allMatch(Character :: isDigit)){
                numAnos = Integer.parseInt(num);
            }
            else{
                JOptionPane.showMessageDialog(this, "Valor Inválido!", "Número de anos ", JOptionPane.ERROR_MESSAGE);
                break;
            }
            String juros = cxJurosMes.getText().replace(',', '.').replace("%", "");
            if (!juros.isEmpty()){
                try{
                    jurosMes = Double.parseDouble(juros); 
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "O valor é invalido, digite apenas números.", "Juros ao mês.", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "O valor não pode ser vazio.", "Juros ao mês. ", JOptionPane.ERROR_MESSAGE);
                break;
            }
            flag = false;
            double valorPoupado = (numAnos*12) * (deposito1 + deposito1*jurosMes/100);
            JOptionPane.showMessageDialog(this,"Total Poupado: " + String.format("%.2f", valorPoupado));
        }
        
    }//GEN-LAST:event_botaoResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poupex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poupex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poupex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poupex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poupex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoResultado;
    private javax.swing.JTextField cxDepMensal;
    private javax.swing.JTextField cxJurosMes;
    private javax.swing.JTextField cxNumAnos;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel textoDeposito;
    private javax.swing.JLabel textoJurosMes;
    private javax.swing.JLabel textoNumAnos;
    // End of variables declaration//GEN-END:variables
}
